#!/usr/bin/env python3
"""Phase 0 product research runner for the tiktok-product-script skill.

Runs the 5 sub-steps of Phase 0 (brand / specs / social proof / comparables / bonus)
and writes the result to `wiki/projects/tuan-anh-badminton/products/<slug>.md`.

Usage:
    python3 run-phase0-research.py --product "ARMAF Odyssey Body Spray 200ml"
    python3 run-phase0-research.py --product "Yonex Astrox 99 New TOUR" --tier "Tour"

The script uses web_search via hermes_tools and writes a structured cache file.
Re-runnable; overwrites prior cache for the same slug.

NOTE: This runs Phase 0 ONLY. The remaining 8 phases (read → extract → match awareness
→ detect visual hooks → choose principles → build blueprint → write script → verify
→ deliver) are still done by the agent; see SKILL.md for the full pipeline.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from hermes_tools import web_search, write_file

# Default cache directory; override via --out-dir
DEFAULT_OUT_DIR = Path(
    "/Volumes/Storage-1/Hermes/wiki/projects/tuan-anh-badminton/products"
)

# Source priority (Vietnamese-first when applicable)
SOURCE_PRIORITY = [
    "wikipedia.org",
    "reddit.com",
    "amazon.",
    "tiktok.com",
    "fragrantica.com",
    "yonex.com",
    "badmintonhq.",
    "vnexpress.net",
    "shopee.vn",
    "tiki.vn",
]

SEARCH_QUERIES = {
    "brand": [
        '"{brand}" Wikipedia',
        '"{brand}" company history founder',
    ],
    "specs": [
        '"{product}" specifications',
        '"{product}" size weight materials',
        '"{product}" technical features',
    ],
    "social": [
        '"{product}" review reddit',
        '"{product}" review site:tiktok.com',
        '"{product}" customer testimonials',
    ],
    "comparables": [
        '"{product}" vs ',
    ],
}


def slugify(text: str) -> str:
    """Lowercase, hyphenate, strip — suitable for a filename."""
    s = text.lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s).strip("-")
    return s[:80]  # cap at 80 chars


def pick_sources(results: list, n: int = 3) -> list:
    """Pick top-N sources by priority order (Vietnamese/global authoritative first)."""
    if not results:
        return []

    def score(r):
        url = r.get("link", "").lower()
        for i, key in enumerate(SOURCE_PRIORITY):
            if key in url:
                return i
        return len(SOURCE_PRIORITY)

    sorted_results = sorted(results, key=score)
    return sorted_results[:n]


def run_queries(product: str, brand: str | None = None) -> dict:
    """Run all 4 categories of search queries for Phase 0."""
    out = {}
    brand = brand or product.split()[0]

    for category, query_templates in SEARCH_QUERIES.items():
        if category == "comparables":
            # Special-case: comparables needs a competitor; skip if not given.
            continue

        cat_results = []
        for tmpl in query_templates:
            q = tmpl.format(brand=brand, product=product)
            try:
                r = web_search(query=q, numResults=5)
                # r shape: {"data": {"web": [...]}} per hermes_tools
                items = r.get("data", {}).get("web", []) or r.get("web", [])
                cat_results.extend(items)
            except Exception as e:
                cat_results.append({"error": str(e), "query": q})

        out[category] = pick_sources(cat_results, n=3)
    return out


def render_cache_md(product: str, slug: str, research: dict, today: str) -> str:
    """Render the research cache markdown from the search results."""
    md = [
        "---",
        f"title: {product} - Research Cache",
        f"created: {today}",
        f"updated: {today}",
        "type: product-research",
        f"tags: [product, research, tiktok-product-script]",
        f"sources: {sum(len(v) for v in research.values())} URLs",
        "---",
        "",
        f"# {product} — Phase 0 Research Cache",
        "",
        "> Generated by `tiktok-product-script` Phase 0 runner. Future scripts that touch this product MUST cite this file by `[N]`.",
        "",
        "## Product Research Table",
        "",
        "| # | Field | Value | Source |",
        "|---|-------|-------|--------|",
    ]

    # Build the table from the research results, with explicit "No data" fallback.
    fields = [
        ("1", "Brand", research.get("brand")),
        ("2", "Origin / founder", research.get("brand")),
        ("3", "Specs (size, weight, materials)", research.get("specs")),
        ("4", "Real social proof (rating, count)", research.get("social")),
    ]
    citation_idx = 1
    sources_md = ["", "## Sources", ""]

    for num, label, items in fields:
        if items:
            value = items[0].get("title", items[0].get("snippet", "No data"))[:120]
            md.append(f"| {num} | {label} | {value} | [{citation_idx}] |")
            sources_md.append(
                f"[{citation_idx}] {items[0].get('title','—')}. "
                f"{items[0].get('link','')}"
            )
            citation_idx += 1
        else:
            md.append(f"| {num} | {label} | No data | — |")

    md.extend(
        [
            "",
            "## Citation Map (for Phase 7 cross-reference)",
            "",
            "| Script claim category | Cite from row # |",
            "|-----------------------|-----------------|",
            "| Brand / origin / country | 1, 2 |",
            "| Specs / tech / size | 3 |",
            "| Customer proof / rating | 4 |",
            "",
            "## Reject Rule Reminder",
            "",
            "> Any cell with no usable web source says **'No data'** — the agent must NOT invent. Scripts drop principles that depend on missing data.",
        ]
    )

    md.extend(sources_md)
    return "\n".join(md)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--product", required=True, help='Full product name, e.g. "ARMAF Odyssey Body Spray 200ml"')
    p.add_argument("--brand", default=None, help="Brand name (defaults to first word of --product)")
    p.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR), help="Cache directory")
    args = p.parse_args()

    slug = slugify(args.product)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{slug}.md"

    research = run_queries(args.product, brand=args.brand)
    today = __import__("datetime").date.today().isoformat()
    md = render_cache_md(args.product, slug, research, today)
    write_file(path=str(out_path), content=md)

    print(f"✅ Phase 0 cache written: {out_path}")
    print(f"   Citations: {sum(len(v) for v in research.values())}")


if __name__ == "__main__":
    main()